# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

bigcolsums <- function(pBigMat, rowInd) {
    .Call('bigstatsr_bigcolsums', PACKAGE = 'bigstatsr', pBigMat, rowInd)
}

bigcolvars <- function(pBigMat, rowInd) {
    .Call('bigstatsr_bigcolvars', PACKAGE = 'bigstatsr', pBigMat, rowInd)
}

incrMat <- function(dest, source) {
    .Call('bigstatsr_incrMat', PACKAGE = 'bigstatsr', dest, source)
}

tcrossprodEigen <- function(res, bM) {
    invisible(.Call('bigstatsr_tcrossprodEigen', PACKAGE = 'bigstatsr', res, bM))
}

tcrossprodEigen2 <- function(res, X, Y) {
    invisible(.Call('bigstatsr_tcrossprodEigen2', PACKAGE = 'bigstatsr', res, X, Y))
}

crossprodEigen5 <- function(X, Y) {
    .Call('bigstatsr_crossprodEigen5', PACKAGE = 'bigstatsr', X, Y)
}

scaling <- function(source, mean, sd) {
    .Call('bigstatsr_scaling', PACKAGE = 'bigstatsr', source, mean, sd)
}

incrSup <- function(pBigMat, source) {
    invisible(.Call('bigstatsr_incrSup', PACKAGE = 'bigstatsr', pBigMat, source))
}

incrAll <- function(pBigMat, source) {
    invisible(.Call('bigstatsr_incrAll', PACKAGE = 'bigstatsr', pBigMat, source))
}

complete <- function(pBigMat) {
    invisible(.Call('bigstatsr_complete', PACKAGE = 'bigstatsr', pBigMat))
}

transpose3 <- function(pBigMat, pBigMat2) {
    invisible(.Call('bigstatsr_transpose3', PACKAGE = 'bigstatsr', pBigMat, pBigMat2))
}

R_squared <- function(pBigMat, y, rowInd) {
    .Call('bigstatsr_R_squared', PACKAGE = 'bigstatsr', pBigMat, y, rowInd)
}

betasRegLin <- function(pBigMat, y, rowInd) {
    .Call('bigstatsr_betasRegLin', PACKAGE = 'bigstatsr', pBigMat, y, rowInd)
}

